name: COD3PTH
url: http://example.org
description: Web2(ctf, bugbounty)

permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  title: ":title - page :num"


gems: [jekyll-paginate-v2]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

